### ISSUE TITLE
Meaningless case L137 because  - NoRouteToHostException <: IOException

### ISSUE THREAD

**Issue by david-lebl** [rockthejvm/zio-course#1]
https://github.com/rockthejvm/zio-course/blob/ce203253cbd909089626ac777960a3a58a4b2f26/src/main/scala/com/rockthejvm/part2effects/ZIOErrorHandling.scala#L136-L137

FIX: Order needs to be switched.

**Comment by daniel-ciocirlan** [comment]
Fixed!
